# Generated by Django 5.0.3 on 2024-03-22 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='event',
        ),
        migrations.CreateModel(
            name='MapContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.event')),
            ],
        ),
    ]
