# Generated by Django 5.0.3 on 2024-03-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
