# Generated by Django 5.0.3 on 2024-03-22 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isgay',
        ),
        migrations.AddField(
            model_name='mapcontactevent',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='mapcontactevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.event'),
        ),
    ]
