# Generated by Django 5.0.4 on 2024-04-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_profile_isgay_mapcontactevent_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
