# Generated by Django 5.0.3 on 2024-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_alter_contact_photo_alter_contact_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contact",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
