# Generated by Django 5.0.3 on 2024-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pronouns',
            field=models.CharField(default='', max_length=255),
        ),
    ]
