# Generated by Django 5.0.3 on 2024-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contact_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
