# Generated by Django 5.0.4 on 2024-04-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('meaning', models.IntegerField(choices=[(1, 'add contact'), (2, 'find contact')])),
            ],
        ),
    ]
